{% set name = "aiohttp-jinja2" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9c22a0e48e3b277fc145c67dd8c3b8f609dab36bce9eb337f70dfe716663c9a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - aiohttp >=3.6.3
    - jinja2 >=2.10.1,<3.0.0a0
    - typing-extensions >=3.7.4

test:
  imports:
    - aiohttp_jinja2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aio-libs/aiohttp-jinja2/
  license: Apache-2.0
  license_file: LICENSE
  summary: jinja2 template renderer for aiohttp.web (http server for asyncio)
  doc_url: http://aiohttp-jinja2.readthedocs.org/

extra:
  recipe-maintainers:
    - apmorton
    - epruesse
