{% set name = "aiohttp-jinja2" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b3d1bf14761675cdb542ea18e04b073a72eef6a2073d160b3199a5810d9f62f7

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - aiohttp >=3.2.0
    - jinja2 >=2.10.1
    - pip
    - python >3.5.3
  run:
    - aiohttp >=3.2.0
    - jinja2 >=2.10.1
    - python >3.5.3

test:
  imports:
    - aiohttp_jinja2

about:
  home: https://github.com/aio-libs/aiohttp-jinja2/
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: jinja2 template renderer for aiohttp.web (http server for asyncio)
  doc_url: http://aiohttp-jinja2.readthedocs.org/

extra:
  recipe-maintainers:
    - epruesse
